export const users = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@efrei.net",
    password: "password",
    role: "ROLE_STUDENT",
    promotions: [1],
    grades: [
      { course: "Maths", grade: 15 },
      { course: "Physics", grade: 12 },
      { course: "English", grade: 18 },
    ],
  },
  {
    id: 2,
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@efrei.net",
    password: "password1",
    role: "ROLE_STUDENT",
    promotions: [2],
    grades: [
      { course: "Maths", grade: 14 },
      { course: "Physics", grade: 16 },
      { course: "English", grade: 17 },
    ],
  },
  {
    id: 3,
    firstName: "Bob",
    lastName: "Johnson",
    email: "bob.johnson@efrei.net",
    password: "password2",
    role: "ROLE_STUDENT",
    promotions: [3],
    grades: [
      { course: "Maths", grade: 15 },
      { course: "Physics", grade: 14 },
      { course: "English", grade: 16 },
    ],
  },
  {
    id: 4,
    firstName: "Charlie",
    lastName: "Williams",
    email: "charlie.williams@efrei.net",
    password: "password3",
    role: "ROLE_STUDENT",
    promotions: [1],
    grades: [
      { course: "Maths", grade: 16 },
      { course: "Physics", grade: 15 },
      { course: "English", grade: 15 },
    ],
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    email: "david.brown@efrei.net",
    password: "password4",
    role: "ROLE_STUDENT",
    promotions: [2],
    grades: [
      { course: "Maths", grade: 17 },
      { course: "Physics", grade: 16 },
      { course: "English", grade: 14 },
    ],
  },
  {
    id: 6,
    firstName: "Michael",
    lastName: "Jones",
    email: "michael.jones@efrei.net",
    password: "password5",
    role: "ROLE_TEACHER",
    promotions: [1, 2],
    course: "Maths",
  },
  {
    id: 7,
    firstName: "Sarah",
    lastName: "Miller",
    email: "sarah.miller@efrei.net",
    password: "password6",
    role: "ROLE_TEACHER",
    promotions: [2, 3],
    course: "Physics",
  },
  {
    id: 8,
    firstName: "James",
    lastName: "Davis",
    email: "james.davis@efrei.net",
    password: "password7",
    role: "ROLE_TEACHER",
    promotions: [1, 3],
    course: "English",
  },
];
