export const users = [
    {
        id: 1,
        firstName: "Kelly",
        lastName: "Kapoor",
        email: "kelly.kapoor@efrei.net",
        password: "password",
        role: "ROLE_STUDENT",
        promotions: [1],
        grades: [
            { course: "Maths", grade: 15 },
            { course: "Physics", grade: 12 },
            { course: "English", grade: 18 },
        ],
    },
    {
        id: 2,
        firstName: "Dwight",
        lastName: "Schrute",
        email: "dwight.schrute@efrei.net",
        password: "password1",
        role: "ROLE_STUDENT",
        promotions: [2],
        grades: [
            { course: "Maths", grade: 13 },
            { course: "Physics", grade: 16 },
            { course: "English", grade: 17 },
        ],
    },
    {
        id: 3,
        firstName: "Bob",
        lastName: "Lennon",
        email: "bob.lennon@efrei.net",
        password: "password2",
        role: "ROLE_STUDENT",
        promotions: [3],
        grades: [
            { course: "Maths", grade: 15 },
            { course: "Physics", grade: 14 },
            { course: "English", grade: 16 },
        ],
    },
    {
        id: 4,
        firstName: "Pam",
        lastName: "Beasly",
        email: "pam.beasly@efrei.net",
        password: "password3",
        role: "ROLE_STUDENT",
        promotions: [1],
        grades: [
            { course: "Physics", grade: 15 },
            { course: "English", grade: 15 },
        ],
    },
    {
        id: 5,
        firstName: "Jim",
        lastName: "Halpert",
        email: "jim.halpert@efrei.net",
        password: "password4",
        role: "ROLE_STUDENT",
        promotions: [2],
        grades: [
            { course: "Maths", grade: 17 },
            { course: "Physics", grade: 16 },
            { course: "English", grade: 14 },
        ],
    },
    {
        id: 6,
        firstName: "Michael",
        lastName: "Scott",
        email: "michael.scott@efrei.net",
        password: "password5",
        role: "ROLE_TEACHER",
        promotions: [1, 2],
        course: "Maths",
    },
    {
        id: 7,
        firstName: "Malek",
        lastName: "Chaouch",
        email: "malek.chaouch@efrei.net",
        password: "password6",
        role: "ROLE_TEACHER",
        promotions: [2, 3],
        course: "Physics",
    },
    {
        id: 8,
        firstName: "Melvin",
        lastName: "Bissor",
        email: "melvin.bissor@efrei.net",
        password: "password7",
        role: "ROLE_TEACHER",
        promotions: [1, 3],
        course: "English",
    },
];
